//! Named constants for OpenSIPS core values — replaces magic numbers in
//! module registration structs.
//!
//! These mirror values from the OpenSIPS C headers. Keep in sync if the
//! upstream changes. Each group references the authoritative source file.

/// Script route-block flags — `route.h` lines 125–134.
///
/// Commands advertise which route contexts they may be called from by
/// OR-ing these flags into `cmd_export_.flags`. OpenSIPS enforces the
/// restriction at config-parse time.
pub mod route_flags {
    use std::ffi::c_int;

    /// Request route (top-level `route { ... }` block).
    pub const REQUEST: c_int = 1;
    /// Failure route (called on negative reply / timeout).
    pub const FAILURE: c_int = 2;
    /// On-reply route (called on any received reply).
    pub const ONREPLY: c_int = 4;
    /// Branch route (called while sending each branch).
    pub const BRANCH: c_int = 8;
    /// Error-handling route.
    pub const ERROR: c_int = 16;
    /// Local-request route (requests generated by OpenSIPS itself).
    pub const LOCAL: c_int = 32;
    /// Startup route (runs once at module-init time).
    pub const STARTUP: c_int = 64;
    /// Timer route.
    pub const TIMER: c_int = 128;
    /// Event route.
    pub const EVENT: c_int = 256;
    /// All route blocks OR'd together.
    pub const ALL: c_int = REQUEST | FAILURE | ONREPLY | BRANCH | ERROR
        | LOCAL | STARTUP | TIMER | EVENT;
}

/// `modparam` value types — `sr_module.h` lines 71–73.
///
/// Used in `param_export_.type_` to tell OpenSIPS how to parse
/// `modparam("module", "name", VALUE)` directives in opensips.cfg.
pub mod param_type {
    /// String parameter (quoted value in cfg).
    pub const STR: u32 = 1 << 0;
    /// Integer parameter (numeric value in cfg).
    pub const INT: u32 = 1 << 1;
    /// Value is passed to a user-supplied fixup function.
    /// OR'd with `STR` or `INT` to select the callback form.
    pub const USE_FUNC: u32 = 1 << (8 * std::mem::size_of::<std::ffi::c_int>() - 1);
}

/// Module classification — `sr_module_deps.h` lines 64–70 (`enum module_type`).
///
/// Drives dependency resolution and reload ordering. Most modules are
/// `DEFAULT`; database backends use `SQLDB` or `CACHEDB`.
pub mod module_type {
    /// Iteration sentinel (not a real module type).
    pub const NULL: u32 = 0;
    /// Default — routing, auth, SIP-message manipulation.
    pub const DEFAULT: u32 = 1;
    /// SQL database backend (db_mysql, db_postgres, ...).
    pub const SQLDB: u32 = 2;
    /// Cache database backend (cachedb_redis, cachedb_nats, ...).
    pub const CACHEDB: u32 = 3;
    /// AAA backend (aaa_radius, aaa_diameter).
    pub const AAA: u32 = 4;
}

/// Dependency-resolution behavior — `sr_module_deps.h` lines 72–76.
///
/// Controls what happens at module-load time when a declared dependency
/// is not met (module not loaded, or param not set).
pub mod dep_behaviour {
    /// Re-order init & destroy if possible; no message on miss.
    pub const SILENT: u32 = 1 << 0;
    /// Re-order init & destroy; warn if dependency not found.
    pub const WARN: u32 = 1 << 1;
    /// Re-order init & destroy; abort module-load on miss.
    pub const ABORT: u32 = 1 << 2;
}

/// Statistics flags — `statistics.h`.
///
/// `c_ushort` field on `stat_export_`. Controls whether a stat can be
/// zeroed by `reset_stat`.
pub mod stat_flags {
    /// Stat value never drops to 0 on `reset_stat`.
    pub const NO_RESET: u16 = 1;
    /// Stat is backed by a getter function rather than a raw counter.
    pub const IS_FUNC: u16 = 2;
}

/// Common combined route-flag literals used across modules — for
/// callers who don't want to repeat `route_flags::REQUEST | route_flags::FAILURE`.
pub mod route {
    use std::ffi::c_int;
    use super::route_flags::*;

    /// Most common: request + failure routes.
    pub const REQ_FAIL: c_int = REQUEST | FAILURE;
    /// Request + failure + on-reply (rate limiters, counters).
    pub const REQ_FAIL_ONREPLY: c_int = REQUEST | FAILURE | ONREPLY;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn route_flags_are_distinct_bits() {
        let all = [
            route_flags::REQUEST, route_flags::FAILURE, route_flags::ONREPLY,
            route_flags::BRANCH, route_flags::ERROR, route_flags::LOCAL,
            route_flags::STARTUP, route_flags::TIMER, route_flags::EVENT,
        ];
        // Each flag must be a power of two, non-zero.
        for f in &all {
            assert!(*f > 0, "flag must be non-zero: {}", f);
            assert!(f.count_ones() == 1, "flag must be single-bit: {}", f);
        }
        // Pairwise disjoint.
        for i in 0..all.len() {
            for j in (i + 1)..all.len() {
                assert_eq!(all[i] & all[j], 0,
                    "flags overlap: {} & {}", all[i], all[j]);
            }
        }
    }

    #[test]
    fn route_all_covers_each_flag() {
        assert_eq!(route_flags::ALL & route_flags::REQUEST, route_flags::REQUEST);
        assert_eq!(route_flags::ALL & route_flags::FAILURE, route_flags::FAILURE);
        assert_eq!(route_flags::ALL & route_flags::EVENT,   route_flags::EVENT);
    }

    #[test]
    fn route_combos_match_bitor() {
        assert_eq!(route::REQ_FAIL, route_flags::REQUEST | route_flags::FAILURE);
        assert_eq!(route::REQ_FAIL_ONREPLY,
                   route_flags::REQUEST | route_flags::FAILURE | route_flags::ONREPLY);
    }

    #[test]
    fn param_type_use_func_is_high_bit() {
        // USE_FUNC is OR'd with STR or INT to tag the param as needing a fixup fn.
        // It must not collide with the low-bit type selectors.
        assert_ne!(param_type::USE_FUNC & param_type::STR, param_type::STR);
        assert_ne!(param_type::USE_FUNC & param_type::INT, param_type::INT);
        // And it must actually be set (non-zero).
        assert!(param_type::USE_FUNC > 0);
    }

    #[test]
    fn module_type_values_match_c_enum() {
        // Locked to sr_module_deps.h enum ordering.
        assert_eq!(module_type::NULL, 0);
        assert_eq!(module_type::DEFAULT, 1);
        assert_eq!(module_type::SQLDB, 2);
        assert_eq!(module_type::CACHEDB, 3);
        assert_eq!(module_type::AAA, 4);
    }
}
